name: CI

on: pull_request

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Install Dependencies
        run: yarn

      - name: Lint
        run: cd tvappweb && yarn lint
